plugins:
  - jest
env:
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
# Include support import.meta.url
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # allows underlining in names for only two constants
